# <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login Screen</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #282c34;
      color: white;
      display: flex;
      align-items: center;
      justify-content: center;
      height: 100vh;
      margin: 0;
    }

    .login-container {
      text-align: center;
      padding: 20px;
      background-color: #444;
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
    }

    input {
      padding: 10px;
      margin: 10px;
      border: none;
      border-radius: 5px;
    }

    button {
      padding: 10px 20px;
      background-color: #61dafb;
      color: #282c34;
      border: none;
      border-radius: 5px;
      cursor: pointer;
    }
  </style>
</head>
<body>
  <div class="login-container">
    <h2>Login</h2>
    <form>
      <input type="text" placeholder="Username" required>
      <br>
      <input type="password" placeholder="Password" required>
      <br>
      <button type="submit">Login</button>
    </form>
  </div>
</body>
</html>
